### ISSUE TITLE
broken railpool preview

### ISSUE THREAD

**Issue by robx** [robx/pzprnode#16]
For this weird puzzle in the db: https://puzz.link/p?railpool/10/10/12345zzzzzzn0050h02081000400001g2800080g00000000

```
Nov 18 18:15:03 nixy pzprnode[3020509]: handling request: /pv?thumb&railpool/10/10/12345zzzzzzn0050h02081000400001g2800080g00000000
Nov 18 18:15:03 nixy pzprnode[3020509]: caught error: TypeError: Cannot read properties of undefined (reading 'pos')
Nov 18 18:15:03 nixy pzprnode[3020509]:     at e.klass.<computed>.drawTapaNumbers (/nix/store/fvzi2kg07nf0acknz749ly9rq1w81pqh-pzprnode/share/node_modules/pzpr/dist/>
Nov 18 18:15:03 nixy pzprnode[3020509]:     at e.klass.<computed>.paint (/nix/store/fvzi2kg07nf0acknz749ly9rq1w81pqh-pzprnode/share/node_modules/pzpr/dist/js/pzpr-va>
Nov 18 18:15:03 nixy pzprnode[3020509]:     at e.klass.<computed>.paintMain (/nix/store/fvzi2kg07nf0acknz749ly9rq1w81pqh-pzprnode/share/node_modules/pzpr/dist/js/pzp>
Nov 18 18:15:03 nixy pzprnode[3020509]:     at e.klass.<computed>.prepaint (/nix/store/fvzi2kg07nf0acknz749ly9rq1w81pqh-pzprnode/share/node_modules/pzpr/dist/js/pzpr>
Nov 18 18:15:03 nixy pzprnode[3020509]:     at e.klass.<computed>.unsuspend (/nix/store/fvzi2kg07nf0acknz749ly9rq1w81pqh-pzprnode/share/node_modules/pzpr/dist/js/pzp>
Nov 18 18:15:03 nixy pzprnode[3020509]:     at j (/nix/store/fvzi2kg07nf0acknz749ly9rq1w81pqh-pzprnode/share/node_modules/pzpr/dist/js/pzpr.js:3:110548)
Nov 18 18:15:03 nixy pzprnode[3020509]:     at f.Puzzle.toBuffer (/nix/store/fvzi2kg07nf0acknz749ly9rq1w81pqh-pzprnode/share/node_modules/pzpr/dist/js/pzpr.js:3:1265>
Nov 18 18:15:03 nixy pzprnode[3020509]:     at /nix/store/fvzi2kg07nf0acknz749ly9rq1w81pqh-pzprnode/share/pzprnode.js:162:23
Nov 18 18:15:03 nixy pzprnode[3020509]:     at /nix/store/fvzi2kg07nf0acknz749ly9rq1w81pqh-pzprnode/share/node_modules/pzpr/dist/js/pzpr.js:3:124609
Nov 18 18:15:03 nixy pzprnode[3020509]:     at Object.setPuzzleClass (/nix/store/fvzi2kg07nf0acknz749ly9rq1w81pqh-pzprnode/share/node_modules/pzpr/dist/js/pzpr.js:3:>
```

**Comment by robx** [comment]
This is a pzprjs issue, fixed there: https://github.com/robx/pzprjs/issues/287
